### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by msgilligan** [hackthefuture/hackthefuture.github.com#12]
I put some basic contribution guidelines in pull request #11.  If the pull request is accepted, those guidelines should be reviewed.

They're pretty basic, but maybe the Google Group isn't the best place -- I think a GitHub issue (suggested as an alternative) might be the best place.

If the pull request isn't accepted, then contribution guidelines need to be written.

**Comment by jdonald** [comment]
Looks good to me. As for the concern raised above, I actually think it is better to keep htf-volunteers@googlegrouops.com as the first place to discuss non-obvious changes, with the Github issue approach as secondary.

If we defaulted to a Github issue each time, then the description and comments get placed in both an issue and a pull request, which leaves the lasting information (and Github comments) in two places cross-linked. Whereas if some good points get brought up on the mailing list, we can paste those into the PR description so that along with any Github comments remains in one #.
